version: '3'
volumes:
  postgres_data: {}
  bundle: {}
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/var/www/book_store
      - bundle:/bundle
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 3000:3000
